### ISSUE TITLE
Can you support English in README?

### ISSUE THREAD

**Issue by hsluoyz** [snowlyg/go-tenancy#14]

**Comment by snowlyg** [comment]
@hsluoyz This pro is not completed

**Comment by hsluoyz** [comment]
@snowlyg is there any ETA for this feature?

**Comment by snowlyg** [comment]
@hsluoyz two month or more time.

**Comment by hsluoyz** [comment]
Thanks!

**Comment by snowlyg** [comment]
> Thanks!

原来是 casbin 的作者啊！大神怎么关注到我的项目了！
